import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Navbar from "./components/Navbar/Navbar";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });


axios.defaults.baseURL = "http://127.0.0.1:8000/";

export const metadata = {
  title: "E-commerce",
  charset: "UTF-8",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
